-- Configured Dry Clean prices copied from the previous Divine Laundry catalog.
-- Items that had no displayed price in the legacy portal are intentionally omitted.
INSERT INTO laundry_services(code, name, category, catalog_group, pricing_unit, unit_rate) VALUES
('SHIRT_DRY', 'White Shirt', 'Dry Clean', 'Men', 'PIECE', 99.00),
('BLAZER_DRY', 'Blazer / Coat', 'Dry Clean', 'Men', 'PIECE', 300.00),
('TSHIRT_DRY_M', 'T-Shirt', 'Dry Clean', 'Men', 'PIECE', 80.00),
('VEST_DRY_M', 'Vest', 'Dry Clean', 'Men', 'PIECE', 149.00),
('UNDERWEAR_DRY_M', 'Under Wear', 'Dry Clean', 'Men', 'PIECE', 59.00),
('PULLOVER_DRY_M', 'Long Pullover', 'Dry Clean', 'Men', 'PIECE', 99.00),
('SWEATPANT_DRY_M', 'Sweat Pants', 'Dry Clean', 'Men', 'PIECE', 119.00),
('CAPRI_DRY_M', 'Capri', 'Dry Clean', 'Men', 'PIECE', 129.00),
('PYJAMA_DRY_M', 'Pyjama', 'Dry Clean', 'Men', 'PIECE', 300.00),
('TRACKPANT_DRY_M', 'Track Pant', 'Dry Clean', 'Men', 'PIECE', 119.00),
('SHORTS_DRY_M', 'Shorts', 'Dry Clean', 'Men', 'PIECE', 109.00),
('LONGCOAT_DRY_M', 'Long Coat', 'Dry Clean', 'Men', 'PIECE', 399.00),
('JEANS_DRY_M', 'Jeans', 'Dry Clean', 'Men', 'PIECE', 139.00),
('ACHKAN_DRY_M', 'Achkan', 'Dry Clean', 'Men', 'PIECE', 199.00),
('TIE_DRY_M', 'Tie', 'Dry Clean', 'Men', 'PIECE', 99.00),
('SHERWANI_DRY_M', 'Sherwani Set', 'Dry Clean', 'Men', 'PIECE', 350.00),
('PETTICOAT_DRY_W', 'Petticoat', 'Dry Clean', 'Women', 'PIECE', 299.00),
('BRASSIERES_DRY_W', 'Brassieres', 'Dry Clean', 'Women', 'PIECE', 99.00),
('TRACKPANT_DRY_W', 'Track Pant', 'Dry Clean', 'Women', 'PIECE', 199.00),
('STOCKINGS_DRY_W', 'Stockings', 'Dry Clean', 'Women', 'PIECE', 199.00),
('PULLOVER_DRY_W', 'Long Pullover', 'Dry Clean', 'Women', 'PIECE', 99.00),
('LONGCOAT_DRY_W', 'Long Coat', 'Dry Clean', 'Women', 'PIECE', 399.00),
('BLAZER_DRY_W', 'Blazer / Coat', 'Dry Clean', 'Women', 'PIECE', 359.00),
('SCARF_DRY_W', 'Scarf', 'Dry Clean', 'Women', 'PIECE', 139.00),
('SLACKS_DRY_W', 'Slacks', 'Dry Clean', 'Women', 'PIECE', 99.00),
('CAPRI_DRY_W', 'Capri', 'Dry Clean', 'Women', 'PIECE', 199.00),
('LEGGINGS_DRY_W', 'Leggings', 'Dry Clean', 'Women', 'PIECE', 199.00),
('JUMPER_DRY_W', 'Jumper', 'Dry Clean', 'Women', 'PIECE', 199.00),
('DANGREE_DRY_W', 'Dangree', 'Dry Clean', 'Women', 'PIECE', 299.00),
('JEANS_DRY_W', 'Jeans', 'Dry Clean', 'Women', 'PIECE', 139.00),
('PANTS_DRY_W', 'Pants', 'Dry Clean', 'Women', 'PIECE', 129.00),
('TSHIRT_DRY_W', 'T-Shirt', 'Dry Clean', 'Women', 'PIECE', 80.00),
('SHIRT_DRY_W', 'Shirt', 'Dry Clean', 'Women', 'PIECE', 80.00),
('BABYBLANKET_DRY_K', 'Baby Blanket', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('TRACKPANT_DRY_K', 'Track Pant', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('LEGGINGS_DRY_K', 'Leggings', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('SWIM_DRY_K', 'Swimming Costume', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('PULLOVER_DRY_K', 'Long Pullover', 'Dry Clean', 'Kids', 'PIECE', 299.00),
('SHERWANI_DRY_K', 'Sherwani', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('DANGREE_DRY_K', 'Dangree', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('JUMPER_DRY_K', 'Jumper', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('SHORTS_DRY_K', 'Shorts', 'Dry Clean', 'Kids', 'PIECE', 49.00),
('CAPRI_DRY_K', 'Capri', 'Dry Clean', 'Kids', 'PIECE', 99.00),
('JEANS_DRY_K', 'Jeans', 'Dry Clean', 'Kids', 'PIECE', 70.00),
('PANTS_DRY_K', 'Pants', 'Dry Clean', 'Kids', 'PIECE', 70.00),
('TSHIRT_DRY_K', 'T-Shirt', 'Dry Clean', 'Kids', 'PIECE', 70.00),
('TABLERUNNER_DRY_H', 'Table Runner', 'Dry Clean', 'Household', 'PIECE', 179.00),
('FOOTMAT_DRY_H', 'Foot Mat', 'Dry Clean', 'Household', 'PIECE', 59.00),
('TABLEMAT_DRY_H', 'Table Mat', 'Dry Clean', 'Household', 'PIECE', 89.00),
('BATHROBE_DRY_H', 'Bath Robe', 'Dry Clean', 'Household', 'PIECE', 89.00),
('SOCKS_DRY_H', 'Socks', 'Dry Clean', 'Household', 'PIECE', 49.00),
('HANDBAG_DRY_H', 'Handbag', 'Dry Clean', 'Household', 'PIECE', 399.00),
('HANDKERCHIEF_DRY_A', 'Handkerchief', 'Dry Clean', 'Accessories', 'PIECE', 49.00),
('TIE_DRY_A', 'Tie', 'Dry Clean', 'Accessories', 'PIECE', 59.00),
('RAINCOAT_DRY_A', 'Rain Coat', 'Dry Clean', 'Accessories', 'PIECE', 299.00),
('HAT_DRY_A', 'Hat', 'Dry Clean', 'Accessories', 'PIECE', 199.00),
('CAP_DRY_A', 'Cap', 'Dry Clean', 'Accessories', 'PIECE', 100.00),
('MUFFLER_DRY_A', 'Muffler', 'Dry Clean', 'Accessories', 'PIECE', 199.00);
