-- Add the 61 priced reference services missing from the initial catalog.
INSERT INTO laundry_services(code, name, category, catalog_group, pricing_unit, unit_rate) VALUES
('JACKET_DRY_M', 'Jacket', 'Dry Clean', 'Men', 'PIECE', 249.00),
('SAFARI_DRY_M', 'Safari', 'Dry Clean', 'Men', 'PIECE', 150.00),
('DHOTI_DRY_M', 'Dhoti', 'Dry Clean', 'Men', 'PIECE', 109.00),
('KURTA_DRY_M', 'Kurta', 'Dry Clean', 'Men', 'PIECE', 340.00),
('SUIT_DRY_M', 'Suit', 'Dry Clean', 'Men', 'PIECE', 100.00),
('SHIRT_DRY_M', 'Shirt', 'Dry Clean', 'Men', 'PIECE', 399.00),
('SWEATER_DRY_M', 'Sweater', 'Dry Clean', 'Men', 'PIECE', 149.00),
('SWEATSHIRT_DRY_M', 'Sweat Shirt', 'Dry Clean', 'Men', 'PIECE', 199.00),
('SWEATER_DRY_W', 'Sweater', 'Dry Clean', 'Women', 'PIECE', 149.00),
('SWEATSHIRT_DRY_W', 'Sweat Shirt', 'Dry Clean', 'Women', 'PIECE', 199.00),
('JACKET_DRY_W', 'Jacket', 'Dry Clean', 'Women', 'PIECE', 249.00),
('SHAWL_DRY_W', 'Shawl', 'Dry Clean', 'Women', 'PIECE', 299.00),
('STOLE_DRY_W', 'Stole', 'Dry Clean', 'Women', 'PIECE', 299.00),
('TOP_DRY_W', 'Top', 'Dry Clean', 'Women', 'PIECE', 399.00),
('SKIRT_LONG_DRY_W', 'Skirt Long', 'Dry Clean', 'Women', 'PIECE', 349.00),
('SKIRT_SHORT_DRY_W', 'Skirt Short', 'Dry Clean', 'Women', 'PIECE', 349.00),
('LEHENGA_DRY_W', 'Lehenga', 'Dry Clean', 'Women', 'PIECE', 349.00),
('DRESS_DRY_W', 'Dress', 'Dry Clean', 'Women', 'PIECE', 259.00),
('BLOUSE_DRY_W', 'Blouse', 'Dry Clean', 'Women', 'PIECE', 299.00),
('SAREE_DRY_W', 'Saree', 'Dry Clean', 'Women', 'PIECE', 349.00),
('DUPATTA_DRY_W', 'Dupatta', 'Dry Clean', 'Women', 'PIECE', 249.00),
('PLAZO_DRY_W', 'Plazo', 'Dry Clean', 'Women', 'PIECE', 279.00),
('SALWAR_DRY_W', 'Salwar', 'Dry Clean', 'Women', 'PIECE', 299.00),
('KURTI_KAMEEZ_DRY_W', 'Kurti / Kameez', 'Dry Clean', 'Women', 'PIECE', 349.00),
('SWEATER_DRY_K', 'Sweater', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('SWEATSHIRT_DRY_K', 'Sweat Shirt', 'Dry Clean', 'Kids', 'PIECE', 129.00),
('JACKET_DRY_K', 'Jacket', 'Dry Clean', 'Kids', 'PIECE', 299.00),
('COAT_DRY_K', 'Coat', 'Dry Clean', 'Kids', 'PIECE', 299.00),
('LEHENGA_DRY_K', 'Lehenga', 'Dry Clean', 'Kids', 'PIECE', 299.00),
('BLOUSE_DRY_K', 'Blouse', 'Dry Clean', 'Kids', 'PIECE', 109.00),
('DUPATTA_DRY_K', 'Dupatta', 'Dry Clean', 'Kids', 'PIECE', 229.00),
('SALWAR_DRY_K', 'Salwar', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('KURTA_DRY_K', 'Kurta', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('DRESS_DRY_K', 'Dress', 'Dry Clean', 'Kids', 'PIECE', 329.00),
('SKIRT_DRY_K', 'Skirt', 'Dry Clean', 'Kids', 'PIECE', 249.00),
('FROCK_DRY_K', 'Frock', 'Dry Clean', 'Kids', 'PIECE', 279.00),
('TOP_DRY_K', 'Top', 'Dry Clean', 'Kids', 'PIECE', 149.00),
('SHIRT_DRY_K', 'Shirt', 'Dry Clean', 'Kids', 'PIECE', 199.00),
('TABLENAPKIN_DRY_H', 'Table Napkin', 'Dry Clean', 'Household', 'PIECE', 179.00),
('TOWELS_DRY_H', 'Towels', 'Dry Clean', 'Household', 'PIECE', 49.00),
('COVERS_DRY_H', 'Covers', 'Dry Clean', 'Household', 'PIECE', 59.00),
('CUSHIONCOVERS_DRY_H', 'Cushion Covers', 'Dry Clean', 'Household', 'PIECE', 119.00),
('SOFACOVER_DRY_H', 'Sofa Cover', 'Dry Clean', 'Household', 'PIECE', 119.00),
('BEDSPREAD_DRY_H', 'BedSpread', 'Dry Clean', 'Household', 'PIECE', 199.00),
('BEDSHEET_DRY_H', 'BedSheet', 'Dry Clean', 'Household', 'PIECE', 349.00),
('DUVET_DRY_H', 'Duvet', 'Dry Clean', 'Household', 'PIECE', 399.00),
('QUILT_DRY_H', 'Quilt', 'Dry Clean', 'Household', 'PIECE', 309.00),
('BLANKET_DRY_H', 'Blanket', 'Dry Clean', 'Household', 'PIECE', 599.00),
('BLIND_DRY_H', 'Blind', 'Dry Clean', 'Household', 'PIECE', 299.00),
('CURTAIN_DRY_H', 'Curtain', 'Dry Clean', 'Household', 'PIECE', 399.00),
('SOFTTOY_DRY_A', 'Soft Toy', 'Dry Clean', 'Accessories', 'PIECE', 299.00),
('GLOVES_DRY_A', 'Gloves', 'Dry Clean', 'Accessories', 'PIECE', 399.00),
('SAREE_IRON', 'Saree', 'Ironing', NULL, 'PIECE', 125.00),
('KURTI_IRON', 'Kurti', 'Ironing', NULL, 'PIECE', 20.00),
('BEDSHEET_IRON', 'Bed Sheet', 'Ironing', NULL, 'PIECE', 50.00),
('BLOUSE_IRON', 'Blouse', 'Ironing', NULL, 'PIECE', 15.00),
('KURTA_IRON', 'Kurta', 'Ironing', NULL, 'PIECE', 25.00),
('PYJAMA_IRON', 'Pyjama', 'Ironing', NULL, 'PIECE', 20.00),
('KIDS_FROCK_IRON', 'Kids Frock', 'Ironing', NULL, 'PIECE', 25.00),
('KIDS_IRON', 'Kids', 'Ironing', NULL, 'PIECE', 14.00),
('DUPATTA_IRON', 'Dupatta', 'Ironing', NULL, 'PIECE', 15.00);
